# Generated by Django 3.0.6 on 2020-05-08 04:46

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('nfcEnabled', models.BooleanField(blank=True, null=True, verbose_name='NFC Enabled')),
                ('qrScanEnabled', models.BooleanField(blank=True, null=True, verbose_name='QR Scanning Enabled')),
                ('dateTimeFormat', models.CharField(blank=True, max_length=30, null=True)),
                ('active', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LocationGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addressLine1', models.CharField(max_length=100)),
                ('addressLine2', models.CharField(max_length=100)),
                ('postCode', models.CharField(max_length=10)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('locationGroup', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.LocationGroup')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationDescription', models.CharField(blank=True, max_length=500, null=True)),
                ('deviceType', models.CharField(max_length=50)),
                ('id1', models.CharField(max_length=30)),
                ('id2', models.CharField(max_length=30)),
                ('status', models.IntegerField()),
                ('enabled', models.BooleanField()),
                ('registeredDate', models.DateTimeField(blank=True, null=True)),
                ('deviceGroup', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.DeviceGroup')),
                ('installationLocation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Location')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('fullname', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('nfcEnabled', models.BooleanField(blank=True, null=True, verbose_name='NFC Enabled')),
                ('qrScanEnabled', models.BooleanField(blank=True, null=True, verbose_name='QR Scanning Enabled')),
                ('sharedLocation', models.BooleanField(blank=True, null=True, verbose_name='Share location after each scan')),
                ('profilePicture', models.ImageField(blank=True, null=True, upload_to='static/images')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.Organization')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
