# Generated by Django 3.0.6 on 2020-07-02 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tmpPassword',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='tmpPasswordExpired',
            field=models.DateTimeField(null=True),
        ),
    ]
