# Generated by Django 3.0.6 on 2020-06-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='adminUsername',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
