# Generated by Django 3.0.6 on 2020-07-24 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
