# Generated by Django 3.0.6 on 2020-05-22 03:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200519_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Device'),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Location'),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='device',
            name='installationLocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Location'),
        ),
        migrations.AlterField(
            model_name='device',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Organization'),
        ),
        migrations.AlterField(
            model_name='location',
            name='addressLine1',
            field=models.CharField(max_length=100, verbose_name='Address Line 1'),
        ),
        migrations.AlterField(
            model_name='location',
            name='addressLine2',
            field=models.CharField(max_length=100, verbose_name='Address Line 2'),
        ),
        migrations.AlterField(
            model_name='location',
            name='geoLocation',
            field=models.CharField(max_length=30, null=True, verbose_name='Map Coordinates'),
        ),
        migrations.AlterField(
            model_name='location',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Organization'),
        ),
        migrations.AlterField(
            model_name='location',
            name='postCode',
            field=models.CharField(max_length=10, verbose_name='Post Code'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='fullname',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Organization'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sharedLocation',
            field=models.BooleanField(blank=True, null=True, verbose_name='Geo Location Enabled'),
        ),
    ]
