# Generated by Django 3.0.6 on 2020-06-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_organization_adminusername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='addressLine2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Address Line 2'),
        ),
    ]
