# Generated by Django 3.0.6 on 2021-02-23 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_checkin_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleViewHistoryPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Role')),
                ('viewGroups', models.ManyToManyField(related_name='viewGroups', to='app.Role')),
            ],
        ),
        migrations.CreateModel(
            name='RolePagePermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pageCode', models.CharField(max_length=50)),
                ('actionCode', models.CharField(max_length=30)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Role')),
            ],
        ),
        migrations.CreateModel(
            name='RoleFeaturePermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featureCode', models.CharField(max_length=50)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Role')),
            ],
        ),
    ]
