# Generated by Django 3.0.6 on 2020-06-25 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200616_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='device',
            name='uid',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='uid'),
        ),
        migrations.AlterField(
            model_name='device',
            name='id1',
            field=models.CharField(max_length=30, verbose_name='ID #1 * '),
        ),
        migrations.AlterField(
            model_name='device',
            name='id2',
            field=models.CharField(max_length=30, verbose_name='ID #2 * '),
        ),
        migrations.AlterField(
            model_name='location',
            name='addressLine1',
            field=models.CharField(max_length=100, verbose_name='Address Line 1 * '),
        ),
        migrations.AlterField(
            model_name='location',
            name='addressLine2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='addressLine2'),
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(max_length=50, verbose_name='City * '),
        ),
        migrations.AlterField(
            model_name='location',
            name='geoLocation',
            field=models.CharField(max_length=30, null=True, verbose_name='Map Coordinates * '),
        ),
        migrations.AlterField(
            model_name='location',
            name='postCode',
            field=models.CharField(max_length=10, verbose_name='Post Code * '),
        ),
        migrations.AlterField(
            model_name='organization',
            name='active',
            field=models.BooleanField(default=False, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Company Name * '),
        ),
        migrations.AlterField(
            model_name='organization',
            name='nfcEnabled',
            field=models.BooleanField(default=False, verbose_name='nfc.enabled'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='qrScanEnabled',
            field=models.BooleanField(default=False, verbose_name='qr.scanning.enabled'),
        ),
        migrations.AlterField(
            model_name='user',
            name='fullname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Full Name * '),
        ),
        migrations.AlterField(
            model_name='user',
            name='nfcEnabled',
            field=models.BooleanField(blank=True, null=True, verbose_name='nfc.enabled'),
        ),
        migrations.AlterField(
            model_name='user',
            name='qrScanEnabled',
            field=models.BooleanField(blank=True, null=True, verbose_name='qr.scanning.enabled'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Role', verbose_name='Role * '),
        ),
        migrations.AlterField(
            model_name='user',
            name='sharedLocation',
            field=models.BooleanField(blank=True, null=True, verbose_name='geolocation.enabled'),
        ),
    ]
