# Generated by Django 3.0.6 on 2020-05-08 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200508_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='organization',
            name='nfcEnabled',
            field=models.BooleanField(default=False, verbose_name='NFC Enabled'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='qrScanEnabled',
            field=models.BooleanField(default=False, verbose_name='QR Scanning Enabled'),
        ),
    ]
