# Generated by Django 3.0.6 on 2021-02-23 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rolefeaturepermission_rolepagepermission_roleviewhistorypermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='GroupFeaturePermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featureCode', models.CharField(max_length=50)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Group')),
            ],
        ),
        migrations.CreateModel(
            name='GroupPagePermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pageCode', models.CharField(max_length=50)),
                ('actionCode', models.CharField(max_length=30)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Group')),
            ],
        ),
        migrations.CreateModel(
            name='GroupViewHistoryPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Group')),
                ('viewGroups', models.ManyToManyField(related_name='viewGroups', to='app.Group')),
            ],
        ),
        migrations.RemoveField(
            model_name='rolepagepermission',
            name='role',
        ),
        migrations.RemoveField(
            model_name='roleviewhistorypermission',
            name='role',
        ),
        migrations.RemoveField(
            model_name='roleviewhistorypermission',
            name='viewGroups',
        ),
        migrations.DeleteModel(
            name='RoleFeaturePermission',
        ),
        migrations.DeleteModel(
            name='RolePagePermission',
        ),
        migrations.DeleteModel(
            name='RoleViewHistoryPermission',
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(to='app.Group', verbose_name='group (*)'),
        ),
    ]
