# Generated by Django 3.0.6 on 2020-06-25 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200625_2230'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=500, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Organization')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Parameter')),
            ],
        ),
    ]
