# Generated by Django 3.0.6 on 2020-05-11 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200508_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicegroup',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.Organization'),
        ),
    ]
