# Generated by Django 3.0.6 on 2020-07-05 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_crudaction_log_logconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Organization'),
        ),
    ]
