# Generated by Django 3.0.6 on 2021-02-23 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210223_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupviewhistorypermission',
            name='viewGroups',
        ),
        migrations.AddField(
            model_name='groupviewhistorypermission',
            name='viewGroup',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='viewGroup', to='app.Group'),
        ),
    ]
