# Generated by Django 3.0.6 on 2020-07-05 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_login_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='modelName',
            field=models.CharField(default='', max_length=100),
        ),
    ]
