# Generated by Django 3.1.5 on 2021-02-26 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210223_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='qrScanEnabled',
        ),
        migrations.RemoveField(
            model_name='user',
            name='qrScanEnabled',
        ),
        migrations.AddField(
            model_name='organization',
            name='createdBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='createdBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='isReseller',
            field=models.BooleanField(default=False, verbose_name='is.reseller'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
