# Generated by Django 3.0.6 on 2020-06-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_tenantparameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='maxLength',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
