# Generated by Django 3.0.6 on 2020-07-05 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_log_modelname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='user',
            new_name='performUser',
        ),
    ]
