# Generated by Django 3.0.6 on 2020-06-25 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_parameter_maxlength'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkin',
            name='geoLocation',
        ),
        migrations.AddField(
            model_name='checkin',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='checkin',
            name='lng',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='checkin',
            name='scanCode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='checkin',
            name='status',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='checkin',
            name='uid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='lng',
            field=models.FloatField(null=True),
        ),
    ]
