# Generated by Django 3.0.6 on 2020-07-05 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200705_0348'),
    ]

    operations = [
        migrations.AddField(
            model_name='logconfig',
            name='acquireNotifyTemplate',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='logconfig',
            name='createNotifyTemplate',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='logconfig',
            name='deleteNotifyTemplate',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='logconfig',
            name='updateNotifyTemplate',
            field=models.CharField(default='', max_length=200),
        ),
    ]
