# Generated by Django 3.0.6 on 2020-06-25 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200626_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Location'),
        ),
    ]
