# Generated by Django 3.0.6 on 2020-05-11 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200512_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='installationLocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.Location'),
        ),
    ]
