# Generated by Django 3.0.6 on 2020-07-05 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200705_0455'),
    ]

    operations = [
        migrations.AddField(
            model_name='logconfig',
            name='releaseNotifyTemplate',
            field=models.CharField(default='', max_length=200),
        ),
    ]
