# Generated by Django 3.0.6 on 2020-06-25 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200626_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='uid',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='uid'),
        ),
    ]
