# Generated by Django 3.0.6 on 2020-07-07 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_logconfig_releasenotifytemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Organization'),
        ),
        migrations.AlterField(
            model_name='device',
            name='id1',
            field=models.CharField(max_length=30, verbose_name='ID#1 (*)'),
        ),
        migrations.AlterField(
            model_name='device',
            name='id2',
            field=models.CharField(max_length=30, verbose_name='ID#2 (*)'),
        ),
        migrations.AlterField(
            model_name='location',
            name='addressLine1',
            field=models.CharField(max_length=100, verbose_name='Address Line 1 (*)'),
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(max_length=50, verbose_name='City (*)'),
        ),
        migrations.AlterField(
            model_name='location',
            name='postCode',
            field=models.CharField(max_length=10, verbose_name='Post Code (*)'),
        ),
        migrations.AlterField(
            model_name='logconfig',
            name='acquireNotifyTemplate',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='logconfig',
            name='createNotifyTemplate',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='logconfig',
            name='deleteNotifyTemplate',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='logconfig',
            name='releaseNotifyTemplate',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='logconfig',
            name='updateNotifyTemplate',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='fullname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Full Name (*)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(to='app.Role', verbose_name='Role (*)'),
        ),
    ]
