# Generated by Django 3.0.6 on 2020-06-25 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200626_0208'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Organization'),
        ),
    ]
