# Generated by Django 3.0.6 on 2020-05-12 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_organization_createddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='createdDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
