# Generated by Django 3.1.5 on 2021-03-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_userfeaturepermission_userpagepermission_userviewhistorypermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='code',
            field=models.CharField(max_length=30),
        ),
    ]
