# Generated by Django 3.0.6 on 2020-07-08 02:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200708_0344'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='viewUsers',
            field=models.ManyToManyField(related_name='view_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='LogView',
        ),
    ]
