# Generated by Django 3.1.5 on 2021-03-10 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210303_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpagepermission',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userviewhistorypermission',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userviewhistorypermission',
            name='viewGroup',
        ),
        migrations.RemoveField(
            model_name='group',
            name='code',
        ),
        migrations.DeleteModel(
            name='UserFeaturePermission',
        ),
        migrations.DeleteModel(
            name='UserPagePermission',
        ),
        migrations.DeleteModel(
            name='UserViewHistoryPermission',
        ),
    ]
