# Generated by Django 3.0.6 on 2020-05-15 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200513_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='createdDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='devicegroup',
            name='createdDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='devicetype',
            name='createdDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='createdDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='locationgroup',
            name='createdDate',
            field=models.DateTimeField(null=True),
        ),
    ]
