# Generated by Django 3.0.6 on 2020-07-08 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20200708_0606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='enabled',
        ),
    ]
