# Generated by Django 3.0.6 on 2020-05-15 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20200515_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='locationGroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.LocationGroup'),
        ),
    ]
