# Generated by Django 3.1.5 on 2021-03-14 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20210310_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='geoLocationEnabled',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='nfcEnabled',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nfcEnabled',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sharedLocation',
        ),
    ]
