# Generated by Django 3.0.6 on 2020-07-08 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_user_enabled'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CRUDAction',
            new_name='LogAction',
        ),
    ]
